function presetgui
  addpath('/usr/share/tascar/matlab');
  javaaddpath('netutil-1.0.0.jar');
  p0 = get(0,'Screensize');
  xr = 0.6;
  yr = 0.6;
  h = figure('NumberTitle','off','Menubar','none',...
	     'Name','Preset GUI',...
	     'Position',round([p0(3)*(1-xr),p0(4)*(1-yr),p0(3)*xr,p0(4)*yr]));
  cLabels = {...
      34,['Picforth'];...
      37,['mute'];...
	    };
  vLabels = [cLabels{:,1}];
  for z=1:3
    y = (z-0.5)/4;
    if mod(z,2)==0
      col = [0.6,0.7,0.6];
    else
      col = [0.6,0.6,0.7];
    end
    uicontrol('style','text','Units','normalized',...
	      'Position',[0.01,y-0.01,0.98,1/9+0.02],...
	      'BackgroundColor',col);
    uicontrol('style','text','Units','normalized',...
	      'Position',[0.02,y,1/13,1/9],...
	      'String',num2str(z),'FontSize',18,...
	      'BackgroundColor',col);
    e2 = 0;
    for e=[10,1:9]
      e2 = e2+1;
      x = (e2+0.5)/12;
      sName = sprintf('%d/%d',z,mod(e,10));
      if any(10*z+e==[12 15 29 33 36 75 95])
	sName = sprintf('%s\nstop',sName);
        uicontrol('style','text',...
                  'units','normalized',...
                  'string','',...
                  'BackgroundColor',[1,0,0],...
                  'position',[x-0.005,y-0.01,1/13+0.01,1/9+0.02]);
      end
      if any(10*z+e==[15])
        uicontrol('style','text',...
                  'units','normalized',...
                  'string','',...
                  'BackgroundColor',[0,0,0.5],...
                  'position',[x-0.005,y-0.01,1/13+0.01,1/9+0.02]);
      end
      idx = find(10*z+e==vLabels);
      if ~isempty(idx)
	sName = sprintf('%s\n%s',sName,cLabels{idx,2});
      end
      pad0 = 2-numel(find(sName==10));
      sName(end+1:end+pad0) = 10;
      if ~any(10*z+e==[119])
          uicontrol('style','togglebutton',...
                    'units','normalized',...
                    'string',sName,...
                    'UserData',10*z+e,...
                    'CallBack',@cbloadpreset,...
                    'position',[x,y,1/13,1/9],...
		    'backgroundcolor',[0.95,0.94,0.94]);
      end
    end
  end

  
function cbloadpreset( varargin )
  val = get(gcbo,'UserData');
  system(sprintf('./loadpreset %d',val));
  set(gcbo,'Value',1,'FontWeight','bold','backgroundcolor',[1,1,0]);
  set(setdiff(findobj('style','togglebutton'),gcbo),'Value',0,'FontWeight','normal','backgroundcolor',[0.95,0.94,0.94]);
